export { displayGreetings } from "./displayGreetings";
export { getRandomGreetings } from "./getRandomGreetings";
export { getFontColorFromHex } from "./getFontColorFromHex";
export { calculateDateDifference } from "./calculateDateDifference";
export { formatDate } from "./formatDate";
export { getTaskCompletionText } from "./getTaskCompletionText";
export { exportTasksToJson } from "./exportTasksToJson";
export { timeAgo } from "./timeAgo";
export { iOS } from "./iOS";